language: ruby
rvm: jruby
cache: bundler
sudo: required

install:
  - sudo apt-get install poppler-utils
  - bundle install
  - npm install

services:
  - postgresql
  - memcached

before_script:
  - psql -c 'create database dc_coming_soon_test;' -U postgres
  - bundle exec rake db:test:prepare
